[package]
name = "rust_sasa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.63.0"

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "my_benchmark"
harness = false
